version: "3.9"
services:

  start:
    image: rdok/gpp:alpine3.12
    volumes: [ .:/app ]
    working_dir: /app
    command: >
      sh -c "
      g++ src/main.cpp -o TripleX.out
      && ./TripleX.out"

  compile:
    image: rdok/gpp:alpine3.12
    volumes: [ .:/app ]
    working_dir: /app
    command: sh -c "g++ src/main.cpp -o TripleX.out"