name: Build

on:
  pull_request:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: |
          docker run \
            --rm \
            --name tripple-x-workbench \
            --volume "/${PWD}":"/app/" \
            --workdir "//app" \
            gcc:9 \
              g++ TripleX.cpp -o TripleX.out