name: CI

on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: docker-compose run --rum compile